name: "Pradipta\'s Test Pipeline"

on:
  pull_request:
    branches:
      - 'develop'

  push:
    branches:
      - 'develop'
      - 'master'
#      - 'feature'

# env:
#   ARTIFACTORY_BUCKET: "mro-devops-esp-artifacts"
#   DEV_ARTIFACTORY_BUCKET: "mro-dev-esp-artifacts-8at6"
#   ARTIFACT_DIRS: "conf dist shared workflows aws snowflake"
#   PYTHON_ARCHITECTURE: "x64"
#   POETRY_VERSION: "1.0.10"
#   TARGET_DIR: "target"
#   ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  get-commit-message:
    runs-on: ubuntu-18.04

    outputs:
      commit-message: ${{ steps.cm.outputs.commit-message}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Print
        run: |
          env | grep GITHUB
          pr_title="${{ github.event.pull_request.title }}"
          echo "$pr_title"
